// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:notesapp/app/interactor/models/notes_model.dart';
import 'package:routefly/routefly.dart';

import 'app/(public)/edit_note_page.dart' as a2;
import 'app/(public)/home_page.dart' as a0;
import 'app/(public)/splash_page.dart' as a1;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.SplashPage(),
        ),
      ),
      RouteEntity(
        key: '/edit_note',
        uri: Uri.parse('/edit_note'),
        routeBuilder: (ctx, settings) {
          final note = settings.arguments as NotesModel;
          return Routefly.defaultRouteBuilder(
            ctx,
            settings,
            a2.EditNotePage(note: note),
          );
        },
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  splash: '/splash',
  editNote: '/edit_note',
);
